environment: production
port: 3000

image:
  repo: web3f/polkadot-watcher-csv-exporter
  tag: latest

config:
  endpoint: "wss://cc3-3.kusama.network"
  port: 3000
  logLevel: info
  exportDir: "./substrate-data-csv"
  bucketUpload:
    enabled: false
    gcpServiceAccount: '/app/service_account/credentials.json'
    gcpProject: ''
    gcpBucketName: '' 

secret:
  gcpServiceAccountValue: ''
    
resources: 
  requests:
    cpu: "100m"
    memory: "500Mi"
  limits:
    cpu: "100m"
    memory: "500Mi" 
