environment: production
port: 3000

image:
  repo: web3f/polkadot-watcher-csv-exporter
  tag: v0.2.1

config:
  endpoint: "wss://cc3-3.kusama.network"
  port: 3000
  logLevel: info
  exportDir: "/app/data-csv"
  bucketUpload:
    enabled: false
    gcpServiceAccount: '/app/service-account/credentials.json'
    gcpProject: ''
    gcpBucketName: '' 
  cronjob:
    enabled: true  

secret:
  gcpServiceAccountValue: |
    {"type":"service_account","project_id":"xxx","private_key_id":"xxx","private_key":"xxx"}

cronjob:
  schedule: "* * * * *"    
    
resources: 
  requests:
    cpu: "100m"
    memory: "500Mi"
  limits:
    cpu: "1200m"
    memory: "1000Mi" 
