version: 2

jobs:
  helmLint:
    docker:
      - image: web3f/ci-commons:v2.4.0
    steps:
      - checkout
      - run:
          command: |
            helm lint ./charts/polkadot-watcher-csv-exporter

  yarnLint:
    docker:
      - image: web3f/node-dind:v0.3.0
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
 

  buildImage:
    docker:
      - image: web3f/ci-commons:v2.4.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/polkadot-watcher-csv-exporter .

  publishImage:
    docker:
      - image: web3f/ci-commons:v2.4.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/polkadot-watcher-csv-exporter

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.4.0
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.4.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh          

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - helmLint:
          filters:
            tags:
              only: /.*/
      - yarnLint:
          filters:
            tags:
              only: /.*/        
      - buildImage:
          context: dockerhub-bot
          filters:
            tags:
              only: /.*/
          requires:
            - helmLint
            - yarnLint
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - helmLint
            - yarnLint        
      - publishImage:
          context: dockerhub-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - buildImage
            - integrationTests
      - publishChart:
          context: github-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - buildImage
            - integrationTests
