endpoint: "wss://kusama-rpc.polkadot.io/"
port: 3000
logLevel: info
exportDir: "./data-csv"
bucketUpload:
  enabled: false
  gcpServiceAccount: '~/Documents/serviceAccount.json'
  gcpProject: 'project-12345'
  gcpBucketName: 'my_bucket'
cronjob:
  enabled: false  