environments:
  ci:
  local:
  production:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:

{{- if or (eq .Environment.Name "ci") (eq .Environment.Name "local") }} 

- name: session-exporter
  chart: ../charts/polkadot-watcher-csv-exporter
  values:
  - ./config/session-exporter-values.yaml.gotmpl

- name: era-scanner
  chart: ../charts/polkadot-watcher-csv-exporter
  values:
  - ./config/era-scanner-values.yaml.gotmpl  

{{- else }}

- name: kusama-session-exporter
  namespace: csv-exporter
  chart: w3f/polkadot-watcher-csv-exporter
  version: v0.10.0
  values:
  - ./config/prod/csv-exporter-values.yaml.gotmpl
  - ./config/prod/kusama/session-exporter-values.yaml.gotmpl

- name: kusama-era-scanner
  namespace: csv-exporter
  chart: w3f/polkadot-watcher-csv-exporter
  version: v0.10.0
  values:
  - ./config/prod/csv-exporter-values.yaml.gotmpl
  - ./config/prod/era/kusama/era-scanner-values.yaml.gotmpl  

- name: polkadot-session-exporter
  namespace: csv-exporter
  chart: w3f/polkadot-watcher-csv-exporter
  version: v0.10.0
  values:
  - ./config/prod/csv-exporter-values.yaml.gotmpl
  - ./config/prod/polkadot/session-exporter-values.yaml.gotmpl

- name: polkadot-era-scanner
  namespace: csv-exporter
  chart: w3f/polkadot-watcher-csv-exporter
  version: v0.10.0
  values:
  - ./config/prod/csv-exporter-values.yaml.gotmpl
  - ./config/prod/polkadot/era-scanner-values.yaml.gotmpl  

{{- end }}
