environments:
  ci:
  local:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:

{{- if or (eq .Environment.Name "ci") (eq .Environment.Name "local") }} 

- name: session-exporter
  chart: ../charts/polkadot-watcher-csv-exporter
  values:
  - ./config/session-exporter-values.yaml.gotmpl

- name: era-scanner
  chart: ../charts/polkadot-watcher-csv-exporter
  values:
  - ./config/era-scanner-values.yaml.gotmpl  

{{- end }}
