environments:
  ci:
  local:
  production:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:

{{- if or (eq .Environment.Name "ci") (eq .Environment.Name "local") }} 

- name: watcher-csv-exporter
  chart: ../charts/polkadot-watcher-csv-exporter
  values:
  - ./config/csv-exporter-watcher-values.yaml.gotmpl

- name: watcher-csv-exporter-scanner
  chart: ../charts/polkadot-watcher-csv-exporter
  values:
  - ./config/csv-exporter-watcher-values.yaml.gotmpl  

{{- else }}

- name: kusama-watcher-csv-exporter
  namespace: kusama
  chart: w3f/polkadot-watcher-csv-exporter
  version: v0.10.0
  values:
  - ./config/prod/csv-exporter-watcher-values.yaml.gotmpl
  - ./config/prod/kusama/csv-exporter-watcher-values.yaml.gotmpl

- name: kusama-watcher-csv-exporter-scanner
  namespace: kusama
  chart: w3f/polkadot-watcher-csv-exporter
  version: v0.10.0
  values:
  - ./config/prod/csv-exporter-watcher-values.yaml.gotmpl
  - ./config/prod/kusama/csv-exporter-watcher-scanner-values.yaml.gotmpl  

- name: polkadot-watcher-csv-exporter
  namespace: polkadot
  chart: w3f/polkadot-watcher-csv-exporter
  version: v0.10.0
  values:
  - ./config/prod/csv-exporter-watcher-values.yaml.gotmpl
  - ./config/prod/polkadot/csv-exporter-watcher-values.yaml.gotmpl

- name: polkadot-watcher-csv-exporter-scanner
  namespace: polkadot
  chart: w3f/polkadot-watcher-csv-exporter
  version: v0.10.0
  values:
  - ./config/prod/csv-exporter-watcher-values.yaml.gotmpl
  - ./config/prod/polkadot/csv-exporter-watcher-scanner-values.yaml.gotmpl  

{{- end }}
