apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  labels:
    app: {{ include "app.name" . }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.config.port }}
  selector:
    app: {{ include "app.name" . }}
